#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
# This formatting makes it apply to all files.
#npm run format && ng lint --fix && git add .

npx pretty-quick --pattern "src/**/*.*(ts|json|html|scss)" --staged  && ng lint --fix
